version: '3.9'

services:

  app:
    build:
      context: ./trading-simulator-app
      dockerfile: Dockerfile
    container_name: trading-simulator-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL:  jdbc:postgresql://timescaledb:5432/trading
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - postgres

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    restart: always
    environment:
      POSTGRES_DB: trading
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - tsdb_data:/var/lib/postgresql/data

  api-client:
    build:
      context: ./api-client
      dockerfile: Dockerfile
    container_name: api-client
    depends_on:
      - app
    entrypoint: ["sh", "-c", "sleep 10 && ./mvnw exec:java"]

volumes:
  tsdb_data:
